/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScorecardsRouteImport } from './routes/scorecards'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthSilentCallbackRouteImport } from './routes/auth.silent-callback'
import { Route as AuthLogoutRouteImport } from './routes/auth.logout'
import { Route as PhaseRouteImport } from './routes/$phase'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PhaseIndexRouteImport } from './routes/$phase/index'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSilentCallbackRoute = AuthSilentCallbackRouteImport.update({
  id: '/auth/silent-callback',
  path: '/auth/silent-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorecardsRoute = ScorecardsRouteImport.update({
  id: '/scorecards',
  path: '/scorecards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const PhaseRoute = PhaseRouteImport.update({
  id: '/$phase',
  path: '/$phase',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhaseIndexRoute = PhaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PhaseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$phase': typeof PhaseRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/silent-callback': typeof AuthSilentCallbackRoute
  '/catalog': typeof CatalogRoute
  '/changelog': typeof ChangelogRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/scorecards': typeof ScorecardsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/$phase/': typeof PhaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/silent-callback': typeof AuthSilentCallbackRoute
  '/catalog': typeof CatalogRoute
  '/changelog': typeof ChangelogRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/scorecards': typeof ScorecardsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/$phase': typeof PhaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$phase': typeof PhaseRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/silent-callback': typeof AuthSilentCallbackRoute
  '/catalog': typeof CatalogRoute
  '/changelog': typeof ChangelogRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/scorecards': typeof ScorecardsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/$phase/': typeof PhaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$phase'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/silent-callback'
    | '/catalog'
    | '/changelog'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/scorecards'
    | '/settings'
    | '/signup'
    | '/status'
    | '/$phase/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/silent-callback'
    | '/catalog'
    | '/changelog'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/scorecards'
    | '/settings'
    | '/signup'
    | '/status'
    | '/$phase'
  id:
    | '__root__'
    | '/'
    | '/$phase'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/silent-callback'
    | '/catalog'
    | '/changelog'
    | '/help'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/scorecards'
    | '/settings'
    | '/signup'
    | '/status'
    | '/$phase/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PhaseRoute: typeof PhaseRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSilentCallbackRoute: typeof AuthSilentCallbackRoute
  CatalogRoute: typeof CatalogRoute
  ChangelogRoute: typeof ChangelogRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ScorecardsRoute: typeof ScorecardsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/silent-callback': {
      id: '/auth/silent-callback'
      path: '/auth/silent-callback'
      fullPath: '/auth/silent-callback'
      preLoaderRoute: typeof AuthSilentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorecards': {
      id: '/scorecards'
      path: '/scorecards'
      fullPath: '/scorecards'
      preLoaderRoute: typeof ScorecardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$phase': {
      id: '/$phase'
      path: '/$phase'
      fullPath: '/$phase'
      preLoaderRoute: typeof PhaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$phase/': {
      id: '/$phase/'
      path: '/'
      fullPath: '/$phase/'
      preLoaderRoute: typeof PhaseIndexRouteImport
      parentRoute: typeof PhaseRoute
    }
  }
}

interface PhaseRouteChildren {
  PhaseIndexRoute: typeof PhaseIndexRoute
}

const PhaseRouteChildren: PhaseRouteChildren = {
  PhaseIndexRoute: PhaseIndexRoute,
}

const PhaseRouteWithChildren = PhaseRoute._addFileChildren(PhaseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PhaseRoute: PhaseRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSilentCallbackRoute: AuthSilentCallbackRoute,
  CatalogRoute: CatalogRoute,
  ChangelogRoute: ChangelogRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ScorecardsRoute: ScorecardsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
