import type {
  ApiToken,
  AuditEvent,
  Environment,
  Integration,
  Invitation,
  Member,
  Organization,
  Plan,
  Project,
  Team,
  Usage,
  Webhook,
} from './types.ts'

export const STUB_ORGS: Organization[] = [
  {
    id: 'org-acme',
    slug: 'acme',
    name: 'Acme Corp',
    description: 'Flagship Adhar tenant',
    region: 'us-east-1',
    plan: 'business',
    createdAt: '2026-01-12T09:00:00Z',
    defaultProjectId: 'proj-adhar-console',
    ssoEnforced: true,
    domain: 'acme.example',
    logoUrl: 'https://i.pravatar.cc/128?u=acme',
  },
  {
    id: 'org-globex',
    slug: 'globex',
    name: 'Globex',
    region: 'eu-west-1',
    plan: 'team',
    createdAt: '2026-02-04T09:00:00Z',
    ssoEnforced: false,
  },
]

export const STUB_MEMBERS: Member[] = [
  {
    userId: 'stub-user-1',
    email: 'tapas.friends@gmail.com',
    name: 'Tapas (you)',
    role: 'owner',
    teams: ['platform', 'dx'],
    joinedAt: '2026-01-12T09:00:00Z',
    lastActiveAt: '2026-04-19T06:14:00Z',
    ssoProvider: 'keycloak',
  },
  {
    userId: 'u-maya',
    email: 'maya@acme.example',
    name: 'Maya Lin',
    role: 'admin',
    teams: ['platform'],
    joinedAt: '2026-01-20T09:00:00Z',
    lastActiveAt: '2026-04-19T05:22:00Z',
    ssoProvider: 'keycloak',
  },
  {
    userId: 'u-rafa',
    email: 'rafa@acme.example',
    name: 'Rafael Ortiz',
    role: 'member',
    teams: ['delivery'],
    joinedAt: '2026-02-14T09:00:00Z',
    lastActiveAt: '2026-04-18T22:05:00Z',
  },
  {
    userId: 'u-sam',
    email: 'sam@acme.example',
    name: 'Samira Khan',
    role: 'billing',
    teams: [],
    joinedAt: '2026-03-01T09:00:00Z',
  },
]

export const STUB_INVITATIONS: Invitation[] = [
  {
    id: 'inv-001',
    email: 'newhire@acme.example',
    role: 'member',
    invitedBy: 'stub-user-1',
    invitedAt: '2026-04-18T10:00:00Z',
    expiresAt: '2026-04-25T10:00:00Z',
    status: 'pending',
  },
]

export const STUB_TEAMS: Team[] = [
  {
    id: 'team-platform',
    slug: 'platform',
    name: 'Platform',
    description: 'Runs the Adhar platform itself',
    memberCount: 2,
    projectCount: 3,
    createdAt: '2026-01-12T09:00:00Z',
  },
  {
    id: 'team-dx',
    slug: 'dx',
    name: 'Developer Experience',
    memberCount: 1,
    projectCount: 2,
    createdAt: '2026-01-18T09:00:00Z',
  },
  {
    id: 'team-delivery',
    slug: 'delivery',
    name: 'Delivery',
    memberCount: 1,
    projectCount: 4,
    createdAt: '2026-01-22T09:00:00Z',
  },
]

export const STUB_PROJECTS: Project[] = [
  {
    id: 'proj-adhar-console',
    slug: 'adhar-console',
    name: 'Adhar Console',
    description: 'Enterprise console for the Adhar platform',
    tenantId: 'acme',
    teams: ['platform', 'dx'],
    primaryRepo: 'acme/adhar-console',
    giteaOrg: 'acme',
    argoProject: 'acme',
    harborProject: 'acme',
    planeProject: 'CON',
    environments: ['env-dev', 'env-staging', 'env-prod'],
    createdAt: '2026-01-12T09:00:00Z',
  },
  {
    id: 'proj-billing',
    slug: 'billing-service',
    name: 'Billing Service',
    description: 'Subscription + invoicing microservice',
    tenantId: 'acme',
    teams: ['delivery'],
    primaryRepo: 'acme/billing-service',
    giteaOrg: 'acme',
    argoProject: 'acme',
    harborProject: 'acme',
    planeProject: 'BIL',
    environments: ['env-dev', 'env-staging', 'env-prod'],
    createdAt: '2026-02-14T09:00:00Z',
  },
  {
    id: 'proj-portal',
    slug: 'customer-portal',
    name: 'Customer Portal',
    tenantId: 'acme',
    teams: ['delivery', 'dx'],
    primaryRepo: 'acme/customer-portal',
    giteaOrg: 'acme',
    argoProject: 'acme',
    harborProject: 'acme',
    environments: ['env-dev', 'env-staging', 'env-prod'],
    createdAt: '2026-03-02T09:00:00Z',
  },
]

export const STUB_ENVIRONMENTS: Environment[] = [
  {
    id: 'env-dev',
    name: 'dev',
    kind: 'dev',
    clusterRef: 'adhar-staging',
    namespace: 'acme-console-dev',
    protectionRules: { requireApproval: false, approvers: [] },
    createdAt: '2026-01-12T09:00:00Z',
  },
  {
    id: 'env-staging',
    name: 'staging',
    kind: 'staging',
    clusterRef: 'adhar-staging',
    namespace: 'acme-console-staging',
    promoteFromEnvId: 'env-dev',
    protectionRules: { requireApproval: true, approvers: ['team:platform'] },
    createdAt: '2026-01-12T09:00:00Z',
  },
  {
    id: 'env-prod',
    name: 'prod',
    kind: 'prod',
    clusterRef: 'adhar-prod',
    namespace: 'acme-console',
    promoteFromEnvId: 'env-staging',
    protectionRules: {
      requireApproval: true,
      approvers: ['team:platform', 'team:delivery'],
      windowsCron: '0 10-16 * * 1-4',
    },
    createdAt: '2026-01-12T09:00:00Z',
  },
]

export const STUB_INTEGRATIONS: Integration[] = [
  {
    id: 'int-gitea',
    tool: 'gitea',
    status: 'connected',
    url: 'https://gitea.adhar.local',
    mode: 'in-cluster',
    version: '1.23.1',
    connectedAt: '2026-01-12T09:00:00Z',
  },
  {
    id: 'int-argocd',
    tool: 'argocd',
    status: 'connected',
    url: 'https://argocd.adhar.local',
    mode: 'in-cluster',
    version: 'v2.13.3',
    connectedAt: '2026-01-12T09:00:00Z',
  },
  {
    id: 'int-kargo',
    tool: 'kargo',
    status: 'connected',
    url: 'https://kargo.adhar.local',
    mode: 'in-cluster',
    version: 'v1.2.0',
    connectedAt: '2026-01-14T09:00:00Z',
  },
  {
    id: 'int-harbor',
    tool: 'harbor',
    status: 'connected',
    url: 'https://harbor.adhar.local',
    mode: 'in-cluster',
    version: 'v2.12.1',
    connectedAt: '2026-01-12T09:00:00Z',
  },
  {
    id: 'int-keycloak',
    tool: 'keycloak',
    status: 'connected',
    url: 'https://keycloak.adhar.local',
    mode: 'in-cluster',
    version: '26.0.5',
    connectedAt: '2026-01-12T09:00:00Z',
  },
  {
    id: 'int-plane',
    tool: 'plane',
    status: 'degraded',
    url: 'https://plane.adhar.local',
    mode: 'in-cluster',
    version: 'v0.24.0',
    connectedAt: '2026-01-20T09:00:00Z',
  },
  {
    id: 'int-kyverno',
    tool: 'kyverno',
    status: 'connected',
    url: 'https://k8s.adhar.local',
    mode: 'in-cluster',
    version: 'v1.13.2',
    connectedAt: '2026-01-12T09:00:00Z',
  },
  {
    id: 'int-grafana',
    tool: 'grafana',
    status: 'connected',
    url: 'https://grafana.adhar.local',
    mode: 'in-cluster',
    version: '11.4.0',
    connectedAt: '2026-01-15T09:00:00Z',
  },
]

export const STUB_TOKENS: ApiToken[] = [
  {
    id: 'tok-ci',
    name: 'ci-runner',
    prefix: 'adhar_pat_ci_',
    scopes: ['projects:read', 'deployments:write'],
    ownerType: 'org',
    ownerId: 'acme',
    createdAt: '2026-02-01T09:00:00Z',
    lastUsedAt: '2026-04-19T06:00:00Z',
    expiresAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'tok-dashboards',
    name: 'grafana-push',
    prefix: 'adhar_pat_gp_',
    scopes: ['metrics:read'],
    ownerType: 'org',
    ownerId: 'acme',
    createdAt: '2026-03-01T09:00:00Z',
    lastUsedAt: '2026-04-19T06:12:00Z',
  },
]

export const STUB_AUDIT: AuditEvent[] = [
  {
    id: 'ev-1',
    actor: { type: 'user', id: 'stub-user-1', label: 'Tapas (you)' },
    action: 'project.created',
    target: { type: 'project', id: 'proj-portal', label: 'customer-portal' },
    outcome: 'success',
    ip: '10.0.3.14',
    userAgent: 'Mozilla/5.0',
    at: '2026-03-02T09:00:12Z',
  },
  {
    id: 'ev-2',
    actor: { type: 'user', id: 'u-maya', label: 'Maya Lin' },
    action: 'member.invited',
    target: { type: 'invitation', id: 'inv-001', label: 'newhire@acme.example' },
    outcome: 'success',
    at: '2026-04-18T10:00:01Z',
  },
  {
    id: 'ev-3',
    actor: { type: 'token', id: 'tok-ci', label: 'ci-runner' },
    action: 'deployment.promote',
    target: { type: 'environment', id: 'env-prod', label: 'acme/adhar-console/prod' },
    outcome: 'success',
    at: '2026-04-19T04:55:02Z',
  },
  {
    id: 'ev-4',
    actor: { type: 'user', id: 'u-rafa', label: 'Rafael Ortiz' },
    action: 'api-token.created',
    target: { type: 'api-token', id: 'tok-local', label: 'rafa-laptop' },
    outcome: 'success',
    at: '2026-04-18T16:02:00Z',
  },
  {
    id: 'ev-5',
    actor: { type: 'system', id: 'kargo', label: 'Kargo' },
    action: 'promotion.auto-rejected',
    target: { type: 'stage', id: 'stage-prod', label: 'acme/billing/prod' },
    outcome: 'failure',
    at: '2026-04-17T22:14:00Z',
  },
]

export const STUB_PLAN: Plan = {
  tier: 'business',
  seats: 25,
  seatsUsed: 12,
  priceMonthly: 1800,
  currency: 'USD',
  renewsAt: '2026-12-01T00:00:00Z',
  paymentMethod: 'card •••• 4242',
  limits: {
    projects: 50,
    environments: 200,
    clusters: 10,
    storageGb: 500,
  },
}

export const STUB_USAGE: Usage = {
  period: '2026-04',
  metrics: {
    projects: 3,
    environments: 9,
    activeUsers: 4,
    deployments: 122,
    apiCalls: 1_843_210,
    logBytesIngested: 214_000_000_000,
    storageUsedGb: 86,
  },
  quotas: {
    projects: 50,
    environments: 200,
    activeUsers: 25,
    deployments: 10_000,
    apiCalls: 10_000_000,
    logBytesIngested: 1_000_000_000_000,
    storageUsedGb: 500,
  },
}

export const STUB_WEBHOOKS: Webhook[] = [
  {
    id: 'wh-slack',
    url: 'https://hooks.slack.com/services/T000/B000/xxxxx',
    events: ['deployment.succeeded', 'deployment.failed', 'rollout.paused'],
    active: true,
    secretSet: true,
    lastDeliveryAt: '2026-04-19T04:55:07Z',
    lastDeliveryStatus: 'success',
  },
]
